### ISSUE TITLE
Refactor to replace unmaintained dependencies

### ISSUE THREAD

**Issue by mkjpryor-stfc** [ESGF/esgf-slcs-server#3]
The current versions of `esgf-slcs-server` dependencies mean we are being bitten by this issue - https://github.com/pyca/cryptography/issues/3605.

Unfortunately, `django_wsgi`, which is used to call out to the original Contrail OnlineCA WSGI application, is totally unmaintained and breaks with the latest LTS of Django, so updating packages is difficult.

This issue proposes refactoring the code to use https://github.com/cedadev/django-onlineca, which is a pure-Django re-implementation, which will allow us to upgrade the `cryptography` version.

**Comment by nathanlcarlson** [comment]
@mkjpryor-stfc With these two merged I believe this issue can be closed. Thanks!

**Comment by mkjpryor-stfc** [comment]
@nathanlcarlson @William-Hill 

Apologies - I didn't think I had merged either this or the playbook PR as I was waiting for someone to review the code.

Glad that they have both been merged now!
